import logging
import re
from typing import List

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document


logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Chunk-level metadata extractors
# ---------------------------------------------------------------------------

def _extract_hoc_ky(text: str) -> str | None:
    match = re.search(r"(?:Hoc\s*ky|Học\s*kỳ)\s*(\d+)\s*(?:nam|năm)\s*(\d+)", text, flags=re.IGNORECASE)
    if not match:
        return None
    return f"Học kỳ {match.group(1)} năm {match.group(2)}"


def _extract_dieu_khoan(text: str) -> str | None:
    match = re.search(r"(?:Dieu|Điều)\s+(\d+)", text, flags=re.IGNORECASE)
    if not match:
        return None
    return f"Điều {match.group(1)}"


# ---------------------------------------------------------------------------
# Crawl-header guard  (defensive strip in case loader didn't strip it)
# ---------------------------------------------------------------------------

def _strip_crawl_header(text: str) -> str:
    """Remove the ``# Key: Value / # ---`` header block generated by crawl_fit_pdfs.py.

    Only acts when the very first line starts with ``# `` to avoid touching
    normal Markdown documents.
    """
    lines = text.split("\n")
    if not lines or not lines[0].startswith("# "):
        return text

    for i, line in enumerate(lines):
        if line.strip() == "# ---":
            return "\n".join(lines[i + 1:]).lstrip("\n").strip()

    return text


# ---------------------------------------------------------------------------
# Metadata merging
# ---------------------------------------------------------------------------

def _merge_chunk_metadata(base_metadata: dict, chunk_text: str) -> dict:
    """Merge per-document base metadata with chunk-level extracted fields.

    Fields resolved at chunk level:
        - hoc_ky     — extracted from chunk text if present
        - dieu_khoan — extracted from chunk text if present

    Fields carried through from base_metadata (set defaults if missing):
        - nganh, loai_van_ban, nam_ban_hanh, source
        - he_dao_tao, tai_lieu   (new crawl-format fields)
    """
    metadata = dict(base_metadata)

    chunk_hoc_ky = _extract_hoc_ky(chunk_text)
    chunk_dieu_khoan = _extract_dieu_khoan(chunk_text)

    if chunk_hoc_ky is not None:
        metadata["hoc_ky"] = chunk_hoc_ky
    else:
        metadata.setdefault("hoc_ky", None)

    if chunk_dieu_khoan is not None:
        metadata["dieu_khoan"] = chunk_dieu_khoan
    else:
        metadata.setdefault("dieu_khoan", None)

    # Document-level fields — populated by loader, only set defaults here
    metadata.setdefault("nganh", None)
    metadata.setdefault("loai_van_ban", "tài liệu khác")
    metadata.setdefault("nam_ban_hanh", None)
    metadata.setdefault("source", "unknown")

    # crawl_fit_pdfs specific fields
    metadata.setdefault("he_dao_tao", None)
    metadata.setdefault("tai_lieu", None)

    return metadata


# ---------------------------------------------------------------------------
# OutlineAwareTextSplitter
# ---------------------------------------------------------------------------

class OutlineAwareTextSplitter:
    """Split Vietnamese academic/legal documents while preserving heading context.

    Heading patterns recognised:
    - Numeric outline : ``1.``, ``1.1.``, ``1.1.1.``
    - Roman numeral   : ``I.``, ``II.``, ``III.``, ``IV.``, ``IX.``, ``X.``
    - Vietnamese legal: ``Chương I``, ``Điều 1``, ``Mục 1``, ``Khoản 1``, ``Phần I``
    """

    def __init__(self, chunk_size: int = 600, chunk_overlap: int = 200) -> None:
        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap

    # ------------------------------------------------------------------
    # Heading detection
    # ------------------------------------------------------------------

    _RE_NUMERIC_HEADING = re.compile(r"^\d+(\.\d+)*\.")
    _RE_ROMAN_HEADING = re.compile(
        r"^(I{1,3}|IV|VI{0,3}|IX|XI{0,3}|XIV|XVI{0,3}|XIX|XX{0,3})\.\s",
        re.IGNORECASE,
    )
    _RE_VN_LEGAL_HEADING = re.compile(
        r"^(Chương|Điều|Mục|Khoản|Phần)\s+[\dIVXivx]+",
        re.IGNORECASE,
    )

    @classmethod
    def _is_heading(cls, line: str) -> bool:
        stripped = line.strip()
        return bool(
            cls._RE_NUMERIC_HEADING.match(stripped)
            or cls._RE_ROMAN_HEADING.match(stripped)
            or cls._RE_VN_LEGAL_HEADING.match(stripped)
        )

    # ------------------------------------------------------------------
    # Text normalisation helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _normalize_whitespace(text: str) -> str:
        return re.sub(r"(\n{2,})", "\n\n", text)

    @staticmethod
    def _nearest_split_point(text: str) -> int:
        split_point = max(text.rfind(" "), text.rfind("!"), text.rfind("?"))
        return split_point if split_point != -1 else len(text)

    # ------------------------------------------------------------------
    # Core splitting logic
    # ------------------------------------------------------------------

    def split_text(self, text: str) -> List[str]:
        # Defensive: strip crawl header in case loader didn't
        text = _strip_crawl_header(text)
        text = self._normalize_whitespace(text)
        lines = text.splitlines()

        chunks: List[str] = []
        current_lines: List[str] = []
        current_len = 0
        last_heading = ""

        for line in lines:
            line_len = len(line)
            if current_len + line_len > self.chunk_size and current_lines:
                chunk = "\n".join(current_lines).strip()

                if len(chunk) > self.chunk_size:
                    split_point = self._nearest_split_point(chunk[: self.chunk_size])
                    chunks.append(chunk[: split_point + 1].strip())
                    overlap_text = chunk[split_point + 1 :]
                else:
                    chunks.append(chunk)
                    overlap_text = chunk[-self.chunk_overlap :]

                overlap_lines = [l for l in overlap_text.splitlines() if l.strip()]

                if last_heading and (not overlap_lines or not self._is_heading(overlap_lines[0])):
                    overlap_lines.insert(0, last_heading)

                current_lines = overlap_lines
                current_len = sum(len(item) + 1 for item in current_lines)

            current_lines.append(line)
            current_len += line_len + 1

            if self._is_heading(line):
                last_heading = line

        if current_lines:
            tail = "\n".join(current_lines).strip()
            if tail:
                chunks.append(tail)

        return chunks

    def create_documents(self, docs: List[Document]) -> List[Document]:
        out: List[Document] = []
        for doc in docs:
            base_metadata = dict(doc.metadata)
            for chunk in self.split_text(doc.page_content):
                metadata = _merge_chunk_metadata(base_metadata=base_metadata, chunk_text=chunk)
                out.append(Document(page_content=chunk, metadata=metadata))
        return out


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def chunk_documents(
    documents: List[Document],
    strategy: str,
    chunk_size: int,
    chunk_overlap: int,
) -> List[Document]:
    logger.info(
        "Chunking documents",
        extra={
            "strategy": strategy,
            "chunk_size": chunk_size,
            "chunk_overlap": chunk_overlap,
            "input_document_count": len(documents),
        },
    )

    if strategy == "recursive":
        splitter = RecursiveCharacterTextSplitter(
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap,
        )
        chunked_documents: List[Document] = []
        for original_doc in documents:
            base_metadata = dict(original_doc.metadata)
            # Defensive: strip header before recursive splitting too
            clean_text = _strip_crawl_header(original_doc.page_content)
            chunks = splitter.split_text(clean_text)
            for chunk in chunks:
                metadata = _merge_chunk_metadata(base_metadata=base_metadata, chunk_text=chunk)
                chunked_documents.append(Document(page_content=chunk, metadata=metadata))
        logger.info("Chunking completed", extra={"output_chunk_count": len(chunked_documents)})
        return chunked_documents

    if strategy == "outline":
        splitter = OutlineAwareTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
        chunked_documents = splitter.create_documents(documents)
        logger.info("Chunking completed", extra={"output_chunk_count": len(chunked_documents)})
        return chunked_documents

    raise ValueError(f"Unknown chunk strategy: {strategy!r}")
